// packages/wc/src/wc/base-popup.ts
import { html, css } from 'lit';
import { BaseElement } from './base-element';
import { property, query } from 'lit/decorators.js';

declare global {
	interface HTMLElementTagNameMap {
		'wc-base-popup': BasePopupElement;
	}
}

export class BasePopupElement extends BaseElement {
	static override tag = 'wc-base-popup';
	static override styles = [this.baseStyles, styles()];

	@query('dialog') dialog!: HTMLDialogElement;

	protected override render() {
		return html`<dialog>
			<slot></slot>
			<button @click=${() => this.dialog.close()} class="btn-close">X</button>
		</dialog> `;
	}

	open() {
		return this.dialog.showModal();
	}

	show() {
		return this.dialog.showModal();
	}

	hide() {
		return this.dialog.close();
	}
}

function styles() {
	return css`
		:host {
			display: block;
			width: min(95%, 1220px);
		}

		dialog {
			margin: 0;
			padding: 0;
		}

		dialog:modal {
			margin: auto;
			border: none;
			border-radius: 10px;
			animation: content-fade-in 800ms forwards ease-out;
		}

		dialog::backdrop {
			background-color: darkorange;
			background-image: linear-gradient(130deg, #ff7a18, #af002d 41.07%, #319197 76.05%);
			filter: blur(0px);
			animation: backdrop-fade-in 800ms forwards ease-out;
			backdrop-filter: blur(20px);
		}

		dialog::slotted(*) {
			margin-inline: auto;
			padding: 0.8rem;
			padding-top: 1.6rem;
		}

		@media (min-width: 800px) {
			::slotted(*) {
				padding-inline: 2rem;
			}
		}

		@keyframes backdrop-fade-in {
			from {
				filter: brightness(0%);
				opacity: 10%;
			}
			to {
				filter: brightness(60%);
				opacity: 90%;
			}
		}

		@keyframes content-fade-in {
			from {
				opacity: 0%;
			}
			to {
				opacity: 100%;
			}
		}

		.btn-close {
			position: fixed;
			top: 1rem;
			right: 1rem;
			z-index: 3;
		}
	`;
}

// packages/app/src/components/BasePopup.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

const opened = ref(false);

const open = () => (opened.value = true);
const close = () => (opened.value = false);

defineExpose({
	open: () => (opened.value = true),
});

const escapeHandler = (e: KeyboardEvent) => {
	if (e.code === 'Escape') {
		close();
	}
};

onMounted(() => {
	window.addEventListener('keydown', escapeHandler);
});

onUnmounted(() => {
	window.removeEventListener('keydown', escapeHandler);
});
</script>

<template>
	<Teleport to="body">
		<div v-if="opened" class="popup">
			<div @click="opened = false" class="backdrop"></div>
			<div class="popup_content">
				<slot />
			</div>
		</div>
	</Teleport>
</template>

<style scoped>
@keyframes blur-in {
	from {
		backdrop-filter: blur(0px) brightness(100%);
	}
	to {
		backdrop-filter: blur(3px) brightness(40%);
	}
}

.popup {
	/* backdrop-filter: brightness(40%) blur(3px); */
	animation: blur-in 200ms forwards;

	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	display: flex;
	justify-content: center;
	align-items: center;
	z-index: 3;
}
.backdrop {
	opacity: 70%;
	width: 100%;
	height: 100%;
	top: 0;
	left: 0;
	position: absolute;

	z-index: 3;
}

.popup_content {
	color: var(--color);
	background-color: var(--bg-color);
	width: min(95%, 1200px);
	padding: 5rem;

	overflow-y: scroll;
	height: 90vh;

	/* background-color: #fff; */
	border-radius: 4px;
	z-index: 10;
	top: 0;

	z-index: 4;
}
</style>
