// src/components/wc/poe-auth.ts
import { html, css } from 'lit';
import { BaseElement } from './base-element';
import { property } from 'lit-element/decorators.js';

declare global {
	interface HTMLElementTagNameMap {
		'wc-poe-auth': PoeAuthElement;
	}
}

const styles = css`
	.poe-auth {
		position: relative;
	}
	.logged-in {
		display: flex;
		align-items: center;
		justify-self: center;
		gap: 1rem;
	}

	.logs {
		opacity: 0.6;
		font-size: 80%;
	}
`;

export class PoeAuthElement extends BaseElement {
	static htmlTag = 'wc-poe-auth';
	static styles = [styles, this.baseStyles];

	@property({ reflect: true }) name: string = '';
	@property({ type: Boolean, reflect: true }) loggedIn: boolean = false;
	render() {
		console.log({ loggedIn: this.loggedIn });
		const logoutButton = html`<button @click=${this.#emitLogoutClicked}>Logout</button>`;
		const loginButton = html`<button @click=${this.#emitLoginClicked}>Login</button>`;

		const template = this.loggedIn
			? html`<div class="logged-in">
					<p>${this.name}</p>
					${logoutButton}
			  </div>`
			: html`<div>${loginButton}</div>`;

		return html`<div class="poe-auth">${template}</div>`;
	}

	#emitLoginClicked() {
		this.emit('login');
	}

	#emitLogoutClicked() {
		this.emit('logout');
	}
}

// src/components/PoeAuth.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia';
import { usePoeOAuth2Store } from '../stores/poeOAuth2Store';
withDefaults(
	defineProps<{
		logs: boolean;
	}>(),
	{ logs: false }
);

const authStore = usePoeOAuth2Store();
const { timeLeft, loggedIn, name, log } = storeToRefs(authStore);
</script>

<template>
	<div class="poe-auth">
		<div class="logged-in" v-if="loggedIn">
			<template v-if="logs && log">
				<div class="logs">
					<p>{{ timeLeft }} seconds left</p>
				</div>
			</template>
			<p>{{ name }}</p>
			<button @click="authStore.logout">Logout</button>
		</div>
		<div v-else>
			<button @click="authStore.login">Login</button>
		</div>
	</div>
</template>

<style scoped>
.poe-auth {
	position: relative;
}
.logged-in {
	display: flex;
	align-items: center;
	justify-self: center;
	gap: 1rem;
}

.logs {
	opacity: 0.6;
	font-size: 80%;
}
</style>
