// src/components/FixedNamesList.vue
<script setup lang="ts">
import ArrowRight from './icons/ArrowRight.vue';

defineProps<{
	fixedNames: Record<string, string>;
}>();
</script>

<template>
	<div class="fixed-names">
		<h2>Automatically fixed typos</h2>
		<ul class="fixed-names-list">
			<li class="list-item" v-for="[inputName, fixedName] in Object.entries(fixedNames)">
				<span class="input-name">{{ inputName }}</span>
				<ArrowRight />
				<span class="fixed-name">{{ fixedName }}</span>
			</li>
		</ul>
	</div>
</template>

<style scoped>
.fixed-names-list {
	margin-top: 2rem;
	/* max-width: 400px; */
}

.list-item {
	display: flex;
	align-items: center;
	gap: 20px;
}

.input-name {
	overflow-x: hidden;
	width: 200px;
	/* background-color: red; */
	opacity: 60%;
}
</style>

// src/components/wc/file-card/fixed-names-list/fixed-names-list.ts
import { html, css, svg } from 'lit';
import { BaseElement } from '../../base-element';
import { property } from 'lit-element/decorators.js';

declare global {
	interface HTMLElementTagNameMap {
		'wc-fixed-names': FixedNamesElement;
	}
}

export class FixedNamesElement extends BaseElement {
	static htmlTag = 'wc-fixed-names';
	static styles = [
		this.baseStyles,
		css`
			.fixed-names-list {
				margin-top: 2rem;
				/* max-width: 400px; */
			}

			.list-item {
				display: flex;
				align-items: center;
				gap: 20px;
			}

			.input-name {
				overflow-x: hidden;
				width: 200px;
				/* background-color: red; */
				opacity: 60%;
			}
		`,
	];

	@property({ reflect: true, type: Number }) width = 32;
	@property({ reflect: true, type: Number }) height = 32;

	render() {
		return html`<svg width=${this.width} height=${this.height} viewBox="0 0 24 24">
			<path
				fill="currentColor"
				d="M9 2c1.8.6 3 2.3 3 4.2c0 2-1.2 3.7-3 4.3v11c0 .3-.2.5-.5.5h-2c-.3 0-.5-.2-.5-.6v-11c-1.8-.6-3-2.3-3-4.2S4.2 2.6 6 2v3.7h3V2m11.6 11l1.4 1.41L15.47 21L12 17.5l1.4-1.41l2.07 2.08L20.6 13"
			></path>
		</svg>`;
	}
}
