// src/components/wc/stashes/tab-badge-group.ts
import { html, css, nothing } from 'lit';
import { BaseElement } from '../base-element';
import { property, state, query } from 'lit-element/decorators.js';
import { StatefulStashTab } from '../../../stores/stash';
import { League, permanentLeagues } from '../../../types';
import { ACTIVE_LEAGUE } from '../../../lib';
import { TabBadgeElement } from './tab-badge';

declare global {
	interface HTMLElementTagNameMap {
		'wc-tab-badge-group': TabBadgeGroupElement;
	}
}

const REMOVE_ONLY = '(Remove-only)';

const styles = css`
	.tab-badge-group {
		display: grid;
		gap: 1rem;
	}
	.filter {
		display: flex;
		gap: 0.4rem;
	}

	.page-controls {
		display: flex;
		gap: 0.4rem;
		align-items: center;
	}

	.page-controls > input {
		width: 5ch;
		text-align: center;
	}

	.hide-remove-only {
		display: flex;
		align-items: center;
		gap: 0.2rem;
	}

	.tabs-total {
		> span {
			color: yellow;
		}
	}

	.list {
		display: flex;
		flex-wrap: wrap;
		list-style: none;
		gap: 5px;
		margin-inline: 1rem;
	}
`;

const filter = (
	stashes: StatefulStashTab[],
	nameQuery: string,
	shouldFilter: boolean,
	hideRemoveOnly: boolean
): StatefulStashTab[] => {
	if (!shouldFilter) return stashes;

	return stashes.filter(({ name }) => {
		if (hideRemoveOnly) {
			if (name.includes(REMOVE_ONLY)) return false;
		}
		return name.toLowerCase().includes(nameQuery.toLowerCase());
	});
};

const paginate = (stashes: StatefulStashTab[], page: number, perPage: number) => {
	const start = (page - 1) * perPage;
	const end = start + perPage;
	return stashes.slice(start, end);
};

const shouldUnlockHideRemoveOnly = (league: League, stashes: StatefulStashTab[]) => {
	return permanentLeagues.includes(league) && stashes.some(({ name }) => name.includes(REMOVE_ONLY));
};

export class TabBadgeGroupElement extends BaseElement {
	static define(tag = 'wc-tab-badge-group') {
		if (!customElements.get(tag)) {
			customElements.define(tag, TabBadgeGroupElement);
			TabBadgeElement.define();
		}
	}
	static htmlTag = 'wc-tab-badge-group';
	static styles = [this.baseStyles, styles];

	@property({ type: Array }) stashes: StatefulStashTab[] = [];
	@property({ reflect: true }) league: League = ACTIVE_LEAGUE;

	@property({ type: Number, reflect: true }) perPage = 50;
	@property({ type: Number, reflect: true }) page = 1;
	@property() nameQuery = '';

	@state() hideRemoveOnly = false;

	@query('input[type="checkbox"]') checkbox!: HTMLInputElement;
	@query('input#per-page') perPageInput!: HTMLInputElement;
	@query('input#page') pageInput!: HTMLInputElement;
	@query('input#filter-stashes-by-name') nameQueryInput!: HTMLInputElement;
	get shouldFilter() {
		return this.stashes.length > 50;
	}

	get withHideRemoveOnly() {
		return shouldUnlockHideRemoveOnly(this.league, this.stashes);
	}

	get filtered() {
		return filter(this.stashes, this.nameQuery, this.shouldFilter, this.hideRemoveOnly);
	}

	get paginated() {
		return paginate(this.filtered, this.page, this.perPage);
	}

	get tabsTotal() {
		return this.stashes.length;
	}

	updated(changed: Map<string, unknown>) {
		if (changed.has('nameQuery') || changed.has('hideRemoveOnly') || changed.has('perPage')) {
			this.page = 1;
		}
	}

	render() {
		const ifWithHideRemoveOnly = this.withHideRemoveOnly
			? html` <div class="hide-remove-only">
					<label for="hide-remove-only">Hide remove-only</label>
					<input
						type="checkbox"
						id="hide-remove-only"
						v-model="hideRemoveOnly"
						.value=${this.hideRemoveOnly}
						@change=${() => (this.hideRemoveOnly = this.checkbox.checked)}
					/>
			  </div>`
			: nothing;

		const filtersSection = this.shouldFilter
			? html`<div v-if="shouldFilter" style="display: flex; flex-wrap: wrap; align-items: center; gap: 2rem">
					<div>
						<div class="filter" v-if="shouldFilter">
							<label for="filter-stashes-by-name">Filter by name</label>
							<input
								type="text"
								id="filter-stashes-by-name"
								.value=${this.nameQuery}
								@input=${this.#onNameQueryInput}
							/>
						</div>
					</div>
					<div class="page-controls" v-if="shouldFilter">
						<button ?disabled=${this.page === 1} @click=${this.decreasePage}>prev</button>
						<input id="page" type="text" .value=${this.page} @input=${this.#onPageInput} />
						<button @click=${this.increasePage}>next</button>
						<label for="per-page">per page</label>
						<input
							id="per-page"
							type="number"
							min="0"
							.value=${this.perPage}
							@input=${this.#onPerPageInput}
						/>
					</div>

					${ifWithHideRemoveOnly}

					<div class="tabs-total"><span>${this.tabsTotal}</span> stash tabs</div>
			  </div>`
			: nothing;

		const paginatedTabs = html`<ul class="list">
			${this.paginated.map(tab => {
				return html`<li>
					<wc-tab-badge
						colour=${tab.metadata?.colour ?? '#fff'}
						name=${tab.name}
						.tabId=${tab.id}
						index=${tab.index}
						.selected=${tab.selected}
					></wc-tab-badge>
				</li>`;
			})}
		</ul>`;

		return html`${filtersSection} ${paginatedTabs} `;
	}

	decreasePage() {
		if (this.page > 1) {
			this.page--;
		}
	}

	increasePage() {
		this.page++;
	}

	#onPageInput() {
		this.page = Number(this.pageInput.value);
	}

	#onPerPageInput() {
		this.perPage = Number(this.perPageInput.value);
	}

	#onNameQueryInput() {
		this.nameQuery = this.nameQueryInput.value;
	}
}

// src/components/stashes/TabBadgeGroup.vue
<script setup lang="ts">
import { StatefulStashTab } from '../../stores/stash';
import { ref, computed, watch } from 'vue';
import { League } from '../../types';
import { filter, shouldUnlockHideRemoveOnly, paginate } from './utils';
import { TabBadgeElement } from '../wc/stashes/tab-badge';
TabBadgeElement.define();
const props = defineProps<{ stashes: StatefulStashTab[]; league: League }>();
const shouldFilter = computed(() => props.stashes.length > 50);
const withHideRemoveOnly = computed(() => shouldUnlockHideRemoveOnly(props.league, props.stashes));
const hideRemoveOnly = ref(false);

const nameQuery = ref('');
const page = ref(1);
const perPage = ref(50);

const filtered = computed(() => filter(props.stashes, nameQuery.value, shouldFilter.value, hideRemoveOnly.value));
const paginated = computed(() => paginate(filtered.value, page.value, perPage.value));
const tabsTotal = computed(() => props.stashes.length);

watch(
	() => [nameQuery.value, perPage.value, hideRemoveOnly.value],
	() => {
		page.value = 1;
	}
);
</script>

<template>
	<div class="tab-badge-group">
		<div v-if="shouldFilter" style="display: flex; flex-wrap: wrap; align-items: center; gap: 2rem">
			<div>
				<div class="filter" v-if="shouldFilter">
					<label for="filter-stashes-by-name">Filter by name</label>
					<input type="text" id="filter-stashes-by-name" v-model="nameQuery" />
				</div>
			</div>
			<div class="page-controls" v-if="shouldFilter">
				<button :disabled="page === 1" @click="page > 1 && page--">prev</button>
				<input type="text" v-model.number="page" />
				<button @click="page++">next</button>
				<label for="per-page">per page</label>
				<input id="per-page" type="number" v-model.number="perPage" min="0" />
			</div>
			<div v-if="withHideRemoveOnly" class="hide-remove-only">
				<label for="hide-remove-only">Hide remove-only</label>
				<input type="checkbox" id="hide-remove-only" v-model="hideRemoveOnly" />
			</div>
			<div class="tabs-total">
				<span>{{ tabsTotal }}</span> stash tabs
			</div>
		</div>
		<ul class="list">
			<li v-for="tab in paginated">
				<wc-tab-badge
					:colour="tab.metadata?.colour ?? '#fff'"
					:name="tab.name"
					:tab-id="tab.id"
					:index="tab.index"
					:selected="tab.selected"
					@selected-changed="(e: CustomEvent<boolean>) => tab.selected = e.detail"
				></wc-tab-badge>
			</li>
		</ul>
	</div>
</template>

<style scoped>
.tab-badge-group {
	display: grid;
	gap: 1rem;
}
.filter {
	display: flex;
	gap: 0.4rem;
}

.page-controls {
	display: flex;
	gap: 0.4rem;
	align-items: center;
}

.page-controls > input {
	width: 5ch;
	text-align: center;
}

.hide-remove-only {
	display: flex;
	align-items: center;
	gap: 0.2rem;
}

.tabs-total {
	> span {
		color: yellow;
	}
}

.list {
	display: flex;
	flex-wrap: wrap;
	list-style: none;
	gap: 5px;
	margin-inline: 1rem;
}
</style>
